(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();document.querySelector("#app").innerHTML=`
  <section class="shell"><header><span class="eyebrow">LOCAL · PRIVATE · OFFLINE · V5</span><h1>糯叽机 ⇄ Float 备份转换器</h1><p>双向转换，文件只在当前浏览器处理，不会上传。</p></header>
    <div class="card"><div class="direction"><button class="dir active" data-dir="toFloat">糯叽机 → Float</button><button class="dir" data-dir="toNuojiji">Float → 糯叽机</button></div>
      <label class="drop"><input id="file" type="file" accept=".gz,application/gzip"><strong id="pickTitle">选择糯叽机 .gz 备份</strong><span id="fileName">选择文件后自动判断大小并给出清理建议</span></label>
      <aside id="sizeAdvice" class="advice" hidden></aside><div class="grid">
        <label><span id="storyLabel">剧情聊天导入方式</span><select id="storyMode"><option value="both">剧情 App + 线下消息</option><option value="offline">仅线下消息</option><option value="story">仅剧情 App</option></select></label>
        <label><span>API Key</span><select id="keyMode"><option value="full">完整迁移</option><option value="blank">留空（安全模式）</option></select></label></div>
      <div class="checks"><label><input id="stripStatus" type="checkbox" checked> 清理状态栏与控制标签</label><label><input id="includeForum" type="checkbox" checked> 论坛与小红书互转</label></div>
      <button id="convert" disabled>开始转换</button><div class="progress" hidden><div id="bar"></div></div><pre id="log">等待选择备份…</pre>
    </div><footer>剧情与线下不会混合：反向转换时按角色建立独立分页。</footer></section>`;const i=e=>document.querySelector(e),p=i("#file"),n=i("#convert"),a=i("#log"),m=i(".progress"),f=i("#bar"),d=i("#sizeAdvice");let l,b="toFloat";function y(e){b=e,document.querySelectorAll(".dir").forEach(s=>s.classList.toggle("active",s.dataset.dir===e)),i("#pickTitle").textContent=e==="toFloat"?"选择糯叽机 .gz 备份":"选择 Float .zip 备份",i("#storyLabel").textContent=e==="toFloat"?"剧情聊天导入方式":"导入糯叽机的剧情分页",p.accept=e==="toFloat"?".gz,application/gzip":".zip,application/zip",l=null,p.value="",n.disabled=!0,d.hidden=!0,i("#fileName").textContent="选择文件后自动判断大小并给出清理建议"}document.querySelectorAll(".dir").forEach(e=>e.addEventListener("click",()=>y(e.dataset.dir)));p.addEventListener("change",()=>{if(l=p.files?.[0],n.disabled=!l,!l)return;const e=l.size/1048576;i("#fileName").textContent=`${l.name} · ${e.toFixed(1)} MB`,d.hidden=!1,d.className=`advice ${e>=100?"warn":"ok"}`,d.textContent=e>=100?`已启用大文件模式（${e.toFixed(1)} MB）：只匹配转换所需模块。建议先在原应用清理音频、壁纸、贴纸、图片缓存、地图缓存、小说及不用的应用数据；浏览器内存不足时仍可能失败。`:"文件大小正常。转换器只生成已选择的核心数据，缓存和不支持的应用数据不会写入结果。"});n.addEventListener("click",async()=>{if(!l)return;n.disabled=!0,m.hidden=!1,f.style.width="3%",a.textContent="正在读取并识别备份…";const e=new Worker(new URL(""+new URL("worker.js",import.meta.url).href,import.meta.url),{type:"module"});e.onmessage=({data:o})=>{if(o.type==="progress"&&(f.style.width=`${o.percent}%`,a.textContent=o.message),o.type==="done"){const c=new Blob([o.buffer],{type:o.filename.endsWith(".gz")?"application/gzip":"application/zip"}),t=document.createElement("a");t.href=URL.createObjectURL(c),t.download=o.filename,t.click(),setTimeout(()=>URL.revokeObjectURL(t.href),3e4),f.style.width="100%",a.textContent=o.report.join(`
`),n.disabled=!1,e.terminate()}o.type==="error"&&(a.textContent=`转换失败：${o.message}`,n.disabled=!1,e.terminate())},e.onerror=o=>{a.textContent=`转换失败：${o.message}`,n.disabled=!1,e.terminate()};const s=await l.arrayBuffer();e.postMessage({buffer:s,direction:b,options:{storyMode:i("#storyMode").value,keyMode:i("#keyMode").value,stripStatus:i("#stripStatus").checked,includeForum:i("#includeForum").checked,largeMode:l.size>=100*1048576}},[s])});
