(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();document.querySelector("#app").innerHTML=`
  <section class="shell"><header><span class="eyebrow">LOCAL · PRIVATE · OFFLINE · V6</span><h1>糯叽机 ⇄ Float 备份转换器</h1><p>双向转换，文件只在当前浏览器处理，不会上传。</p></header>
    <div class="card"><div class="direction"><button class="dir active" data-dir="toFloat">糯叽机 → Float</button><button class="dir" data-dir="toNuojiji">Float → 糯叽机</button></div>
      <label class="drop"><input id="file" type="file" accept=".gz,application/gzip"><strong id="pickTitle">选择糯叽机 .gz 备份</strong><span id="fileName">选择文件后自动判断大小并给出清理建议</span></label>
      <aside id="sizeAdvice" class="advice" hidden></aside><div class="grid">
        <label><span id="storyLabel">剧情聊天导入方式</span><select id="storyMode"><option value="both">剧情 App + 线下消息</option><option value="offline">仅线下消息</option><option value="story">仅剧情 App</option></select></label>
        <label><span>API Key</span><select id="keyMode"><option value="full">完整迁移</option><option value="blank">留空（安全模式）</option></select></label></div>
      <div class="checks"><label><input id="stripStatus" type="checkbox" checked> 清理状态栏与控制标签</label><label id="forumOption"><input id="includeForum" type="checkbox" checked> 糯叽机论坛导入 Float 小红书</label></div>
      <button id="convert" disabled>开始转换</button><div class="progress" hidden><div id="bar"></div></div><pre id="log">等待选择备份…</pre>
    </div><footer>剧情与线下不会混合：反向转换时按角色建立独立分页。</footer></section>`;const i=e=>document.querySelector(e),u=i("#file"),s=i("#convert"),a=i("#log"),m=i(".progress"),b=i("#bar"),d=i("#sizeAdvice");let l,p="toFloat";function y(e){p=e,document.querySelectorAll(".dir").forEach(n=>n.classList.toggle("active",n.dataset.dir===e)),i("#pickTitle").textContent=e==="toFloat"?"选择糯叽机 .gz 备份":"选择 Float .zip 备份",i("#storyLabel").textContent=e==="toFloat"?"剧情聊天导入方式":"导入糯叽机的剧情分页",i("#forumOption").hidden=e==="toNuojiji",u.accept=e==="toFloat"?".gz,application/gzip":".zip,application/zip",l=null,u.value="",s.disabled=!0,d.hidden=!0,i("#fileName").textContent="选择文件后自动判断大小并给出清理建议"}document.querySelectorAll(".dir").forEach(e=>e.addEventListener("click",()=>y(e.dataset.dir)));u.addEventListener("change",()=>{if(l=u.files?.[0],s.disabled=!l,!l)return;const e=l.size/1048576;i("#fileName").textContent=`${l.name} · ${e.toFixed(1)} MB`,d.hidden=!1,d.className=`advice ${e>=100?"warn":"ok"}`,d.textContent=e>=100?`已启用大文件模式（${e.toFixed(1)} MB）：只匹配转换所需模块。建议先在原应用清理音频、壁纸、贴纸、图片缓存、地图缓存、小说及不用的应用数据；浏览器内存不足时仍可能失败。`:"文件大小正常。转换器只生成已选择的核心数据，缓存和不支持的应用数据不会写入结果。"});s.addEventListener("click",async()=>{if(!l||p==="toNuojiji"&&!window.confirm(`Float → 糯叽机转换注意事项

1. 因糯叽机是非开源项目，目前只能转换角色核心相关数据：角色卡、角色私聊消息、此时此刻剧情、世界书、用户信息、朋友圈和 API 设置。Float 群聊、角色记忆及小红书/论坛不转换。

2. 导入后请检查角色卡性别。若角色列表暂时没有显示消息，请进入通讯录并点击对应好友查看。角色记忆目前无法可靠转换，请根据原有聊天内容手动总结。

是否继续转换？`))return;s.disabled=!0,m.hidden=!1,b.style.width="3%",a.textContent="正在读取并识别备份…";const e=new Worker(new URL(""+new URL("worker-DoOt0ckr.js",import.meta.url).href,import.meta.url),{type:"module"});e.onmessage=({data:o})=>{if(o.type==="progress"&&(b.style.width=`${o.percent}%`,a.textContent=o.message),o.type==="done"){const c=new Blob([o.buffer],{type:o.filename.endsWith(".gz")?"application/gzip":"application/zip"}),t=document.createElement("a");t.href=URL.createObjectURL(c),t.download=o.filename,t.click(),setTimeout(()=>URL.revokeObjectURL(t.href),3e4),b.style.width="100%",a.textContent=o.report.join(`
`),s.disabled=!1,e.terminate()}o.type==="error"&&(a.textContent=`转换失败：${o.message}`,s.disabled=!1,e.terminate())},e.onerror=o=>{a.textContent=`转换失败：${o.message}`,s.disabled=!1,e.terminate()};const n=await l.arrayBuffer();e.postMessage({buffer:n,direction:p,options:{storyMode:i("#storyMode").value,keyMode:i("#keyMode").value,stripStatus:i("#stripStatus").checked,includeForum:p==="toFloat"&&i("#includeForum").checked,largeMode:l.size>=100*1048576}},[n])});
